name: price-fetcher - build

on:
  push:
    branches:
      - main
    paths:
      - 'price-fetcher/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/docker_build_push.yml
    with:
      project_path: ./price-fetcher
      dockerfile_path: ./price-fetcher/Dockerfile
      image_name: price-fetcher